# Generated by Django 3.0.4 on 2020-03-28 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('date', models.DateField(default=datetime.datetime(2020, 3, 28, 13, 19, 18, 378942, tzinfo=utc))),
                ('content', models.TextField()),
            ],
        ),
    ]
