# Generated by Django 3.0.4 on 2020-03-28 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 13, 25, 12, 746183, tzinfo=utc)),
        ),
    ]
