# Generated by Django 3.0.4 on 2020-04-11 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200328_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 20, 52, 4, 291697, tzinfo=utc)),
        ),
    ]
